<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{a00b47c4-e886-489a-8899-d512157aae0f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	m : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[m := m + 1;
PrgMqttCom();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>