///////////////////////////////////////////////////////////////////////////////
// TcIotDriversServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TcIotDrivers = 0x02020000;
#define SRVNAME_TCIOTDRIVERS "TcIotDrivers"


TCOM_DECL_INTERFACE("9A71A723-3928-4C02-AC02-EFD30999A041", ITcIotMqttOwner)
TCOM_DECL_INTERFACE("D7C4D81F-CFAB-4103-B89E-6F6731DBFC1C", ITcIotMqttClient)
TCOM_DECL_INTERFACE("08F36648-871A-43A8-9D47-4E77905A6063", ITcIotMqttClientTls)

enum EOsSocketState {
	OS_SOCKET_ERR_CONN_PENDING = -1,
	OS_SOCKET_ERR_SUCCESS = 0,
	OS_SOCKET_ERR_NOMEM = 1,
	OS_SOCKET_ERR_CREATE_PROTOCOL = 2,
	OS_SOCKET_ERR_INVAL = 3,
	OS_SOCKET_ERR_NO_CONN = 4,
	OS_SOCKET_ERR_CONN_REFUSED = 5,
	OS_SOCKET_ERR_NOT_FOUND = 6,
	OS_SOCKET_ERR_CONN_LOST = 7,
	OS_SOCKET_ERR_TLS = 8,
	OS_SOCKET_ERR_PAYLOAD_SIZE = 9,
	OS_SOCKET_ERR_NOT_SUPPORTED = 10,
	OS_SOCKET_ERR_AUTH = 11,
	OS_SOCKET_ERR_ACL_DENIED = 12,
	OS_SOCKET_ERR_UNKNOWN = 13,
	OS_SOCKET_ERR_ERRNO = 14,
	OS_SOCKET_ERR_EAI = 15,
	OS_SOCKET_ERR_PROXY = 16,
	OS_SOCKET_ERR_TLS_CA_NOTFOUND = 17,
	OS_SOCKET_ERR_TLS_CERT_NOTFOUND = 18,
	OS_SOCKET_ERR_TLS_KEY_NOTFOUND = 19,
	OS_SOCKET_ERR_TLS_CA_INVALID = 20,
	OS_SOCKET_ERR_TLS_CERT_INVALID = 21,
	OS_SOCKET_ERR_TLS_KEY_INVALID = 22,
	OS_SOCKET_ERR_TLS_VERIFY_FAIL = 23,
	OS_SOCKET_ERR_TLS_SETUP = 24,
	OS_SOCKET_ERR_TLS_HANDSHAKE_FAIL = 25,
	OS_SOCKET_ERR_TLS_CIPHER_INVALID = 26,
	OS_SOCKET_ERR_TLS_VERSION_INVALID = 27,
	OS_SOCKET_ERR_TLS_PSK_INVALID = 28,
	OS_SOCKET_ERR_TLS_CRL_NOTFOUND = 29,
	OS_SOCKET_ERR_TLS_CRL_INVALID = 30,
	OS_SOCKET_ERR_FINALIZE_DISCONNECT = 31,
	OS_SOCKET_ERR_BIND = 32,
	OS_SOCKET_ERR_BIND_ADDR_INUSE = 33,
	OS_SOCKET_ERR_BIND_ADDR_INVAL = 34,
	OS_SOCKET_ERR_CREATE = 35,
	OS_SOCKET_ERR_CREATE_TYPE = 36,
	OS_SOCKET_ERR_CONN = 37,
	OS_SOCKET_ERR_CONN_TIMEDOUT = 38,
	OS_SOCKET_ERR_CONN_HOSTUNREACH = 39,
	OS_SOCKET_ERR_TLS_CERT_EXPIRED = 40,
	OS_SOCKET_ERR_TLS_CN_MISMATCH = 41,
};

typedef EOsSocketState ETcIotSocketState;

enum ETcIotMqttClientState {
	MQTT_ERR_CONN_PENDING = OS_SOCKET_ERR_CONN_PENDING,
	MQTT_ERR_SUCCESS = OS_SOCKET_ERR_SUCCESS,
	MQTT_ERR_NOMEM = OS_SOCKET_ERR_NOMEM,
	MQTT_ERR__PROTOCOL = OS_SOCKET_ERR_CREATE_PROTOCOL,
	MQTT_ERR_INVAL = OS_SOCKET_ERR_INVAL,
	MQTT_ERR_NO_CONN = OS_SOCKET_ERR_NO_CONN,
	MQTT_ERR_CONN_REFUSED = OS_SOCKET_ERR_CONN_REFUSED,
	MQTT_ERR_NOT_FOUND = OS_SOCKET_ERR_NOT_FOUND,
	MQTT_ERR_CONN_LOST = OS_SOCKET_ERR_CONN_LOST,
	MQTT_ERR_TLS = OS_SOCKET_ERR_TLS,
	MQTT_ERR_PAYLOAD_SIZE = OS_SOCKET_ERR_PAYLOAD_SIZE,
	MQTT_ERR_NOT_SUPPORTED = OS_SOCKET_ERR_NOT_SUPPORTED,
	MQTT_ERR_AUTH = OS_SOCKET_ERR_AUTH,
	MQTT_ERR_ACL_DENIED = OS_SOCKET_ERR_ACL_DENIED,
	MQTT_ERR_UNKNOWN = OS_SOCKET_ERR_UNKNOWN,
	MQTT_ERR_ERRNO = OS_SOCKET_ERR_ERRNO,
	MQTT_ERR_EAI = OS_SOCKET_ERR_EAI,
	MQTT_ERR_PROXY = OS_SOCKET_ERR_PROXY,
	MQTT_ERR_TLS_CA_NOTFOUND = OS_SOCKET_ERR_TLS_CA_NOTFOUND,
	MQTT_ERR_TLS_CERT_NOTFOUND = OS_SOCKET_ERR_TLS_CERT_NOTFOUND,
	MQTT_ERR_TLS_KEY_NOTFOUND = OS_SOCKET_ERR_TLS_KEY_NOTFOUND,
	MQTT_ERR_TLS_CA_INVALID = OS_SOCKET_ERR_TLS_CA_INVALID,
	MQTT_ERR_TLS_CERT_INVALID = OS_SOCKET_ERR_TLS_CERT_INVALID,
	MQTT_ERR_TLS_KEY_INVALID = OS_SOCKET_ERR_TLS_KEY_INVALID,
	MQTT_ERR_TLS_VERIFY_FAIL = OS_SOCKET_ERR_TLS_VERIFY_FAIL,
	MQTT_ERR_TLS_SETUP = OS_SOCKET_ERR_TLS_SETUP,
	MQTT_ERR_TLS_HANDSHAKE_FAIL = OS_SOCKET_ERR_TLS_HANDSHAKE_FAIL,
	MQTT_ERR_TLS_CIPHER_INVALID = OS_SOCKET_ERR_TLS_CIPHER_INVALID,
	MQTT_ERR_TLS_VERSION_INVALID = OS_SOCKET_ERR_TLS_VERSION_INVALID,
	MQTT_ERR_TLS_PSK_INVALID = OS_SOCKET_ERR_TLS_PSK_INVALID,
	MQTT_ERR_TLS_CRL_NOTFOUND = OS_SOCKET_ERR_TLS_CRL_NOTFOUND,
	MQTT_ERR_TLS_CRL_INVALID = OS_SOCKET_ERR_TLS_CRL_INVALID,
	MQTT_ERR_FINALIZE_DISCONNECT = OS_SOCKET_ERR_FINALIZE_DISCONNECT,
	MQTT_ERR_BIND = OS_SOCKET_ERR_BIND,
	MQTT_ERR_BIND_ADDR_INUSE = OS_SOCKET_ERR_BIND_ADDR_INUSE,
	MQTT_ERR_BIND_ADDR_INVAL = OS_SOCKET_ERR_BIND_ADDR_INVAL,
	MQTT_ERR_CREATE = OS_SOCKET_ERR_CREATE,
	MQTT_ERR_CREATE_TYPE = OS_SOCKET_ERR_CREATE_TYPE,
	MQTT_ERR_CONN = OS_SOCKET_ERR_CONN,
	MQTT_ERR_CONN_TIMEDOUT = OS_SOCKET_ERR_CONN_TIMEDOUT,
	MQTT_ERR_CONN_HOSTUNREACH = OS_SOCKET_ERR_CONN_HOSTUNREACH,
	MQTT_ERR_TLS_CERT_EXPIRED = OS_SOCKET_ERR_TLS_CERT_EXPIRED,
	MQTT_ERR_TLS_CN_MISMATCH = OS_SOCKET_ERR_TLS_CN_MISMATCH,
};

	
const PTCID PID_IotMqttClientId			= DrvID_TcIotDrivers | 0x0101;
const PTCID PID_IotMqttTcpPort			= DrvID_TcIotDrivers | 0x0103;
const PTCID PID_IotMqttKeepAlive			= DrvID_TcIotDrivers | 0x0104;
const PTCID PID_IotMqttUserName			= DrvID_TcIotDrivers | 0x0106;
const PTCID PID_IotMqttPassword			= DrvID_TcIotDrivers | 0x0107;
const PTCID PID_IotMqttWillTopic			= DrvID_TcIotDrivers | 0x0108;
const PTCID PID_IotMqttWillPayload		= DrvID_TcIotDrivers | 0x0109;
const PTCID PID_IotMqttWillQos			= DrvID_TcIotDrivers | 0x010A;
const PTCID PID_IotMqttWillRetain		= DrvID_TcIotDrivers | 0x010B;
const PTCID PID_IotMqttDefaultTopic		= DrvID_TcIotDrivers | 0x010C;
const PTCID PID_IotMqttPublish			= DrvID_TcIotDrivers | 0x010D;
const PTCID PID_IotMqttSubscribe			= DrvID_TcIotDrivers | 0x010E;
const PTCID PID_IotMqttUnubscribe		= DrvID_TcIotDrivers | 0x010F;
const PTCID PID_IotMqttLastPayload		= DrvID_TcIotDrivers | 0x0110;
const PTCID PID_IotMqttAutoConnect		= DrvID_TcIotDrivers | 0x0111;
const PTCID PID_IotMqttIsConnected		= DrvID_TcIotDrivers | 0x0112;
const PTCID PID_IotMqttHostName			= DrvID_TcIotDrivers | 0x0113;
const PTCID PID_IotMqttDataFormat		= DrvID_TcIotDrivers | 0x0114;
const PTCID PID_IotMqttWhiteSpaces		= DrvID_TcIotDrivers | 0x0115;
const PTCID PID_IotMqttTlsCaFile			= DrvID_TcIotDrivers | 0x0116;
const PTCID PID_IotMqttTlsCaPath			= DrvID_TcIotDrivers | 0x0117;
const PTCID PID_IotMqttTlsCertFile		= DrvID_TcIotDrivers | 0x0118;
const PTCID PID_IotMqttTlsKeyFile		= DrvID_TcIotDrivers | 0x0119;
const PTCID PID_IotMqttTlsInsecure		= DrvID_TcIotDrivers | 0x011A;
const PTCID PID_IotMqttTlsVersion		= DrvID_TcIotDrivers | 0x011B;
const PTCID PID_IotMqttTlsCiphers		= DrvID_TcIotDrivers | 0x011C;
const PTCID PID_IotMqttAdsServer			= DrvID_TcIotDrivers | 0x011D;
const PTCID PID_IotMqttAzureSAS			= DrvID_TcIotDrivers | 0x011E;
const PTCID PID_IotMqttAzureGeneratePrefix	= DrvID_TcIotDrivers | 0x011F;
const PTCID PID_IotMqttTopicPrefix		= DrvID_TcIotDrivers | 0x0120;
const PTCID PID_IotMqttTlsCa				= DrvID_TcIotDrivers | 0x0121;
const PTCID PID_IotMqttTlsCert			= DrvID_TcIotDrivers | 0x0122;
const PTCID PID_IotMqttTlsKey				= DrvID_TcIotDrivers | 0x0123;
const PTCID PID_IotMqttTlsKeyPwd			= DrvID_TcIotDrivers | 0x0124;
const PTCID PID_IotMqttTlsCrlFile		= DrvID_TcIotDrivers | 0x0125;
const PTCID PID_IotMqttTlsCrl				= DrvID_TcIotDrivers | 0x0126;
const PTCID PID_IotMqttTlsPskId			= DrvID_TcIotDrivers | 0x0127;
const PTCID PID_IotMqttTlsPskKey			= DrvID_TcIotDrivers | 0x0128;
const PTCID PID_IotMqttTlsPskPwd			= DrvID_TcIotDrivers | 0x0129;
const PTCID PID_IotMqttTlsPskIdCaseS	= DrvID_TcIotDrivers | 0x012A;
const PTCID PID_IotMqttTlsIgnoreExpiration	= DrvID_TcIotDrivers | 0x012B;
const PTCID PID_IotMqttResendTimeout	= DrvID_TcIotDrivers | 0x0143;
const PTCID PID_IotMqttConnectionState = DrvID_TcIotDrivers | 0x0144;
const PTCID PID_IotMqttFinalizeTimeout	= DrvID_TcIotDrivers | 0x0145;
const PTCID PID_IotMqttPublisherSendCnt		= DrvID_TcIotDrivers | 0x0146;
const PTCID PID_IotMqttMaxMessageSize			= DrvID_TcIotDrivers | 0x0147;
const PTCID PID_IotMqttPublisherResendCnt		= DrvID_TcIotDrivers | 0x0148;
const PTCID PID_IotMqttSubscriberRecvDropCnt = DrvID_TcIotDrivers | 0x0149;
const PTCID PID_IotMqttSubscriberRecvCnt		= DrvID_TcIotDrivers | 0x014A;
const PTCID PID_IotMqttConnectionCnt			= DrvID_TcIotDrivers | 0x0150;


// category ids
const		CATTCID	CATID_TcIotMqtt_Device				= DrvID_TcIotDrivers | 0x0001;

