<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="MAIN" Id="{cc69c161-152a-42d3-b915-bdc8cc2f5bde}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	m : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[m := m + 1;

PrgMqttCom();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="2" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>