///////////////////////////////////////////////////////////////////////////////
// CppIotMqttSampleModule.h
#pragma once

#include "CppIotMqttSampleInterfaces.h"
#include "Iot/TcIotDriversInterfaces.h"


class CCppIotMqttSampleModule 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
	, public ITcIotMqttOwner
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_CppIotMqttSampleCCppIotMqttSampleModule)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CCppIotMqttSampleModule();
	virtual	~CCppIotMqttSampleModule();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

	// ITcIotMqttOwner
	virtual HRESULT TCOMAPI OnMqttMessage(PCCH topic, PVOID payload, ULONG length, TcIotMqttQos qos, bool repeated);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	STRING255 m_TopicPub;
	STRING255 m_TopicSub;
	ULONG m_PublishCnt;
	bool m_Connected;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
	ITcIotMqttClientPtr m_spMqttClient;
///</AutoGeneratedContent>

	// TODO: Custom variable
	UINT m_counter;
	bool m_bSubscribed;

	STRING255 m_sTopicRcv;
	STRING255 m_sPayloadRcv;
};
