///////////////////////////////////////////////////////////////////////////////
// CppIotMqttSampleInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "CppIotMqttSampleServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
