///////////////////////////////////////////////////////////////////////////////
// CppIotMqttSampleModule.cpp
#include "TcPch.h"
#pragma hdrstop

#include "CppIotMqttSampleModule.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CCppIotMqttSampleModule
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CCppIotMqttSampleModule
BEGIN_INTERFACE_MAP(CCppIotMqttSampleModule)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
	INTERFACE_ENTRY(IID_ITcIotMqttOwner, ITcIotMqttOwner)
///</AutoGeneratedContent>
END_INTERFACE_MAP()


IMPLEMENT_ITCOMOBJECT(CCppIotMqttSampleModule)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CCppIotMqttSampleModule)
IMPLEMENT_ITCADI(CCppIotMqttSampleModule)
IMPLEMENT_ITCWATCHSOURCE(CCppIotMqttSampleModule)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CCppIotMqttSampleModule 
BEGIN_SETOBJPARA_MAP(CCppIotMqttSampleModule)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_CppIotMqttSampleModuleTopicPub, m_TopicPub)
	SETOBJPARA_VALUE(PID_CppIotMqttSampleModuleTopicSub, m_TopicSub)
	SETOBJPARA_VALUE(PID_CppIotMqttSampleModulePublishCnt, m_PublishCnt)
	SETOBJPARA_VALUE(PID_CppIotMqttSampleModuleConnected, m_Connected)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	SETOBJPARA_ITFPTR(PID_CppIotMqttSampleModuleMqttClient, m_spMqttClient)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CCppIotMqttSampleModule 
BEGIN_GETOBJPARA_MAP(CCppIotMqttSampleModule)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_CppIotMqttSampleModuleTopicPub, m_TopicPub)
	GETOBJPARA_VALUE(PID_CppIotMqttSampleModuleTopicSub, m_TopicSub)
	GETOBJPARA_VALUE(PID_CppIotMqttSampleModulePublishCnt, m_PublishCnt)
	GETOBJPARA_VALUE(PID_CppIotMqttSampleModuleConnected, m_Connected)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
	GETOBJPARA_ITFPTR(PID_CppIotMqttSampleModuleMqttClient, m_spMqttClient)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CCppIotMqttSampleModule
BEGIN_OBJPARAWATCH_MAP(CCppIotMqttSampleModule)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CCppIotMqttSampleModule
BEGIN_OBJDATAAREA_MAP(CCppIotMqttSampleModule)
///<AutoGeneratedContent id="ObjectDataAreaMap">
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CCppIotMqttSampleModule::CCppIotMqttSampleModule()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, m_counter(0)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	memset(&m_TopicPub, 0, sizeof(m_TopicPub));
	memset(&m_TopicSub, 0, sizeof(m_TopicSub));
	m_PublishCnt = 0;
	m_Connected = FALSE;
///</AutoGeneratedContent>
	
	m_bSubscribed = false;
	memset(&m_sTopicRcv, 0, sizeof(m_sTopicRcv));
	memset(&m_sPayloadRcv, 0, sizeof(m_sPayloadRcv));

}

///////////////////////////////////////////////////////////////////////////////
CCppIotMqttSampleModule::~CCppIotMqttSampleModule() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CCppIotMqttSampleModule)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CCppIotMqttSampleModule::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CCppIotMqttSampleModule::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	if (m_spMqttClient.HasOID())
		hr = m_spSrv->TcQuerySmartObjectInterface(m_spMqttClient);
	else
		hr = ADS_E_INVALIDPARM;

	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before this method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		m_spMqttClient = NULL;
		RemoveModuleFromCaller(); 
	}
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CCppIotMqttSampleModule::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	RemoveModuleFromCaller();
	m_spMqttClient = NULL;

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CCppIotMqttSampleModule::SetObjStateSP()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CCppIotMqttSampleModule::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	ETcIotMqttClientState eState;
	
	m_counter++;
	
	if (m_counter%100 == 0 && m_Connected )
	{
		HRESULT hr;
		char szMessage[32];

		if (!m_bSubscribed)
		{
			if (SUCCEEDED(hr = m_spMqttClient->MqttSubscribe(m_TopicSub, TcIotMqttQos::AtMostOnceDelivery)))
			{
				m_bSubscribed = true;
			}
			else
			{
				//Add your error handling here
			}
		}

		m_PublishCnt++;
		sprintf(szMessage, "MyMessage %d", m_PublishCnt);
		if (FAILED(hr = m_spMqttClient->MqttPublish(m_TopicPub, szMessage, (UINT)strlen(szMessage) + 1)))
		{
			//Add your error handling here
		}
	}

	if (SUCCEEDED(m_spMqttClient->MqttExecute(THIS_CAST(ITcIotMqttOwner), true, &eState)))
	{
		if (eState == ETcIotMqttClientState::MQTT_ERR_SUCCESS)
			m_Connected = TRUE;
		else
			m_Connected = FALSE;
	}

	return S_OK;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CCppIotMqttSampleModule::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CCppIotMqttSampleModule::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);
	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;
	m_Trace.Log(tlVerbose, FLEAVEA);
}


///<AutoGeneratedContent id="ImplementationOf_ITcIotMqttOwner">
HRESULT CCppIotMqttSampleModule::OnMqttMessage(PCCH topic, PVOID payload, ULONG length, TcIotMqttQos qos, bool repeated)
{
	size_t nPayloadRcvLen;
		strncpy(m_sTopicRcv, topic, sizeof(m_sTopicRcv)-1);
		
		nPayloadRcvLen = min(length, sizeof(m_sPayloadRcv)-1);
		memcpy(m_sPayloadRcv, payload, nPayloadRcvLen);
		return S_OK;
}
///</AutoGeneratedContent>