///////////////////////////////////////////////////////////////////////////////
// CppIotMqttSampleClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "CppIotMqttSampleClassFactory.h"
#include "CppIotMqttSampleServices.h"
#include "CppIotMqttSampleVersion.h"
#include "CppIotMqttSampleModule.h"

BEGIN_CLASS_MAP(CCppIotMqttSampleClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_CppIotMqttSampleCCppIotMqttSampleModule, SRVNAME_CPPIOTMQTTSAMPLE "!CCppIotMqttSampleModule", CCppIotMqttSampleModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CCppIotMqttSampleClassFactory::CCppIotMqttSampleClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_CPPIOTMQTTSAMPLE));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(CppIotMqttSample));
#endif //defined(TCDBG_UNIT_VERSION)
}

