///////////////////////////////////////////////////////////////////////////////
// CppIotMqttSampleServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_CppIotMqttSample = 0x3F000000;
#define SRVNAME_CPPIOTMQTTSAMPLE "CppIotMqttSample"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_CppIotMqttSampleCCppIotMqttSampleModule = {0xc1cd9fd8,0x9ba6,0x4379,{0xb7,0x4b,0x9f,0x16,0x04,0xbb,0xed,0xc6}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_CppIotMqttSampleModuleTopicPub = 0x00000002;
const PTCID PID_CppIotMqttSampleModuleTopicSub = 0x00000003;
const PTCID PID_CppIotMqttSampleModulePublishCnt = 0x00000004;
const PTCID PID_CppIotMqttSampleModuleConnected = 0x00000005;
const PTCID PID_CppIotMqttSampleModuleMqttClient = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_
typedef CHAR STRING255[256];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_0001000000FF_INCLUDED_)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
