<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="MAIN" Id="{e4c4f930-8f79-4895-a54f-5256381f76bd}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	m : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[m := m + 1;

PrgMqttCom();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="9" Count="2" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>